"""update-3

Revision ID: 911c25ff9d83
Revises: 1476f4bb7712
Create Date: 2025-12-28 17:13:26.044017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911c25ff9d83'
down_revision: Union[str, None] = '1476f4bb7712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('intent', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'intent')
    # ### end Alembic commands ###
